services:
  app:
    build: .
    container_name: my-node-app
    ports:
      - "5173:5173"   # Vite frontend
      - "3001:3001" # Uncomment if your backend exposes another port
    volumes:
      # - C:/Users/fede/Documents/DockerMount:/video  # Mount local folder into container
      - C:/Users/fede/Videos/GD:/video:ro  # Read Only for input folder
      - C:/Users/fede/Videos/GD/Trimmed:/video/Trimmed  # Output folder
    environment:
      - INPUT_FOLDER=/video
      - OUTPUT_FOLDER=/video/Trimmed
    working_dir: /app
    command: npx concurrently "npm:dev:frontend" "npm:dev:server"
    restart: unless-stopped