services:
  app:
    build: .
    image: ftambler/ffmpeg-gui:latest
    container_name: ffmpeg-gui
    ports:
      - "3000:3000"
    volumes:
      - C:/Users/fede/Videos/GD:/video:ro
      - C:/Users/fede/Videos/GD/Trimmed:/video/Trimmed
    environment:
      - INPUT_FOLDER=/video
      - OUTPUT_FOLDER=/video/Trimmed
    restart: unless-stopped